Loosen cookie name/value validation
jshttp/cookie pull request #210
Opened 2024-11-15 21:53 UTC by blakeembrey

Closes https://github.com/jshttp/cookie/issues/191. All keys and values are supported in Safari. Although older or other browsers may not support some of these characters, I don't think we should be restricting it unless it's a security issue.

2024-11-15 22:00 UTC, ctcpip requested changes
you've actually eliminated some of what you previously allowed...

2024-11-15 22:04 UTC, ctcpip approved these changes
ignore previous comment, I was squinting wrongly at the regex

2024-11-17 18:31 UTC, UlisesGascon approved these changes

2024-11-20 17:21 UTC, merged

2025-01-27 19:25 UTC, benmccann commented
A couple of questions about this:
- Is 1.0.2 fully backward compatible with the pre-1.0 releases?
- Is there any need to avoid cookies with special characters such as `:` still?

2025-01-29 04:38 UTC, blakeembrey commented
> Is 1.0.2 fully backward compatible with the pre-1.0 releases?

No, the breaking changes can be viewed here: https://github.com/jshttp/cookie/releases/tag/v1.0.0

Assuming you are only referring to this PR and pre-0.7 releases, still no. The regex is stricter than what was previously causing a security issue.

> Is there any need to avoid cookies with special characters such as : still?

Cookies could contain `:`, but names were stricter following the RFC and didn't allow `:`. They now allow `:` again with this change.